// ====================================
// <copyright file="BootstrapTemplate.cs" company="Spicco D'Aura">
// Copyright (c) Spicco D'Aura. All rights reserved.
// Licensed under the CC BY-SA 1.0 License.
// </copyright>
// ====================================

using System.Text;
using System.Collections.Generic;

namespace pyro.Avian.Templates;

internal static class BootstrapTemplate
{
    public static string Render(Dictionary<string, string> embeddedAssemblies)
    {
        var matchCases = new StringBuilder();

        foreach (var assembly in embeddedAssemblies)
        {
            matchCases.AppendLine($@"                case ""{assembly.Key}"":");
            matchCases.AppendLine($@"                    return OnResolveBase64({assembly.Value});");
        }

        return $@"// <auto-generated>This file is automatically generated by pyro.Avian.BootstrapTemplate.</auto-generated>
using System;
using System.Reflection;
using System.Runtime.CompilerServices;

namespace Pyro.Generated
{{
    internal static class PyroBootstrap
    {{
        [ModuleInitializer]
        internal static void Initialize()
        {{
            AppDomain.CurrentDomain.AssemblyResolve += OnAssemblyResolve;
        }}

        private static Assembly? OnAssemblyResolve(object? sender, ResolveEventArgs args)
        {{
            string shortName = new AssemblyName(args.Name).Name ?? string.Empty;

            switch (shortName)
            {{
{matchCases}
                default:
                    return null;
            }}
        }}

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static Assembly OnResolveBase64(string base64Data)
        {{
            if (string.IsNullOrEmpty(base64Data)) return null!;
            byte[] rawBytes = Convert.FromBase64String(base64Data);
            return Assembly.Load(rawBytes);
        }}
    }}
}}";
    }
}